/*
 * rcc.c
 *
 *  Created on: Mar 13, 2025
 *      Author: FlY DeN
 */

#include "rcc.h"


void CMSIS_Clock_Config(void) {
	//Configure flash WS and VOS
	MODIFY_REG(FLASH->ACR, FLASH_ACR_LATENCY_Msk,
			0b000 << FLASH_ACR_LATENCY_Pos);
	MODIFY_REG(PWR->CR1, PWR_CR1_VOS_Msk, 0b01 << PWR_CR1_VOS_Pos);

	//Configure RCC
	CLEAR_BIT(RCC->CR, RCC_CR_PLLON);
	CLEAR_BIT(RCC->CR, RCC_CR_CSSON);
	CLEAR_BIT(RCC->CR, RCC_CR_HSEON);
	CLEAR_BIT(RCC->CR, RCC_CR_HSEBYP);
	SET_BIT(RCC->CR, RCC_CR_HSION);
	while (READ_BIT(RCC->CR, RCC_CR_HSIRDY) == RESET);
	MODIFY_REG(RCC->CR, RCC_CR_HSIDIV_Msk, 0b000 << RCC_CR_HSIDIV_Pos);
	MODIFY_REG(RCC->CFGR, RCC_CFGR_HPRE_Msk, 0b0000 << RCC_CFGR_HPRE_Pos);
	MODIFY_REG(RCC->CFGR, RCC_CFGR_PPRE_Msk, 0b000 << RCC_CFGR_PPRE_Pos);
	MODIFY_REG(RCC->CFGR, RCC_CFGR_SW_Msk, 0b000 << RCC_CFGR_SW_Pos);
	MODIFY_REG(RCC->CFGR, RCC_CFGR_SWS_Msk, 0b000 << RCC_CFGR_SWS_Pos);
}

